// <auto-generated />
using System;
using Dooter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dooter.Migrations.BookmarkDB
{
    [DbContext(typeof(BookmarkDBContext))]
    [Migration("20221128005539_Bookmarks")]
    partial class Bookmarks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dooter.Models.Bookmark", b =>
                {
                    b.Property<int>("BookmarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("latitude")
                        .HasColumnType("float");

                    b.Property<double?>("longitude")
                        .HasColumnType("float");

                    b.HasKey("BookmarkID");

                    b.ToTable("Bookmarks");

                    b.HasData(
                        new
                        {
                            BookmarkID = 1,
                            Name = "Bookmark 1",
                            Rating = 3.5,
                            latitude = 1.0,
                            longitude = 1.0
                        },
                        new
                        {
                            BookmarkID = 2,
                            Name = "Bookmark 2",
                            Rating = 3.5,
                            latitude = 1.0,
                            longitude = 1.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
